# Generated by Django 5.0.4 on 2024-04-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_id', models.CharField(max_length=100)),
                ('type', models.IntegerField()),
                ('typeEs', models.CharField(max_length=100)),
                ('typeEu', models.CharField(max_length=100)),
                ('nameEs', models.TextField()),
                ('nameEu', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('publicationDate', models.DateField()),
                ('language', models.CharField(max_length=10)),
                ('sourceNameEs', models.CharField(max_length=100)),
                ('sourceNameEu', models.CharField(max_length=100)),
                ('sourceUrlEs', models.CharField(max_length=255)),
                ('sourceUrlEu', models.CharField(max_length=255)),
                ('descriptionEs', models.TextField()),
                ('descriptionEu', models.TextField()),
                ('municipalityEs', models.CharField(max_length=100)),
                ('municipalityEu', models.CharField(max_length=100)),
                ('municipalityLatitude', models.FloatField()),
                ('municipalityLongitude', models.FloatField()),
                ('municipalityNoraCode', models.TextField(max_length=100)),
                ('provinceNoraCode', models.TextField(max_length=100)),
                ('establishmentEs', models.TextField(max_length=100)),
                ('establishmentEu', models.TextField(max_length=100)),
                ('urlEventEs', models.TextField(max_length=100)),
                ('urlEventEu', models.TextField(max_length=100)),
                ('urlNameEs', models.TextField(max_length=100)),
                ('urlNameEu', models.TextField(max_length=100)),
                ('images', models.CharField(max_length=255)),
            ],
        ),
    ]
