# Generated by Django 5.0.4 on 2024-05-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='attachment',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='companyEs',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='companyEu',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='openingHoursEs',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='openingHoursEu',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='placeEs',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='placeEu',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='priceEs',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='priceEu',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='purchaseUrlEs',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='purchaseUrlEu',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
