# Generated by Django 5.0.4 on 2024-05-01 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_events_attachment_events_companyes_events_companyeu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created',
            field=models.DateField(default=datetime.datetime(2024, 5, 1, 20, 32, 6, 789027)),
        ),
        migrations.AddField(
            model_name='events',
            name='updated',
            field=models.DateField(default=datetime.datetime(2024, 5, 1, 20, 32, 6, 789027)),
        ),
    ]
