# Generated by Django 5.0.4 on 2024-05-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0003_events_created_events_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='updated',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
    ]
