# Generated by Django 5.0.4 on 2024-05-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0004_alter_events_created_alter_events_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='sourceUrlEs',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='sourceUrlEu',
            field=models.TextField(max_length=255),
        ),
    ]
