# Generated by Django 5.0.4 on 2024-05-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0005_alter_events_sourceurles_alter_events_sourceurleu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='sourceUrlEs',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='sourceUrlEu',
            field=models.TextField(),
        ),
    ]
