# Generated by Django 5.0.4 on 2024-05-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0006_alter_events_sourceurles_alter_events_sourceurleu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='images',
            field=models.CharField(max_length=1000),
        ),
    ]
