# Generated by Django 5.0.4 on 2024-05-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0007_alter_events_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created',
            field=models.DateField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='updated',
            field=models.DateField(auto_created=True, auto_now_add=True, null=True),
        ),
    ]
