# Generated by Django 5.0.4 on 2024-05-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0008_alter_events_created_alter_events_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='online',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
