# Generated by Django 5.0.4 on 2024-05-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0009_events_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='urlOnlineEs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='urlOnlineEu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
