# Generated by Django 5.0.4 on 2024-05-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0010_events_urlonlinees_events_urlonlineeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='companyEs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='companyEu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='placeEs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='placeEu',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='purchaseUrlEs',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='purchaseUrlEu',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='sourceNameEs',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='sourceNameEu',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='typeEs',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='typeEu',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='events',
            name='urlOnlineEs',
            field=models.CharField(max_length=1100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='urlOnlineEu',
            field=models.CharField(max_length=1100, null=True),
        ),
    ]
