# Generated by Django 5.0.4 on 2024-05-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0011_alter_events_companyes_alter_events_companyeu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='attachment',
            field=models.TextField(max_length=1100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='companyEs',
            field=models.CharField(max_length=1100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='companyEu',
            field=models.CharField(max_length=1100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='establishmentEs',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='events',
            name='establishmentEu',
            field=models.CharField(max_length=105),
        ),
        migrations.AlterField(
            model_name='events',
            name='municipalityEs',
            field=models.CharField(max_length=108),
        ),
        migrations.AlterField(
            model_name='events',
            name='municipalityEu',
            field=models.CharField(max_length=108),
        ),
        migrations.AlterField(
            model_name='events',
            name='municipalityNoraCode',
            field=models.CharField(max_length=107),
        ),
        migrations.AlterField(
            model_name='events',
            name='online',
            field=models.CharField(max_length=1100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='openingHoursEs',
            field=models.CharField(max_length=102, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='openingHoursEu',
            field=models.CharField(max_length=102, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='placeEs',
            field=models.CharField(max_length=1100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='placeEu',
            field=models.CharField(max_length=1100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='priceEs',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='priceEu',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='provinceNoraCode',
            field=models.CharField(max_length=106),
        ),
        migrations.AlterField(
            model_name='events',
            name='purchaseUrlEs',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='purchaseUrlEu',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='urlEventEs',
            field=models.CharField(max_length=104),
        ),
        migrations.AlterField(
            model_name='events',
            name='urlEventEu',
            field=models.CharField(max_length=104),
        ),
        migrations.AlterField(
            model_name='events',
            name='urlNameEs',
            field=models.CharField(max_length=103),
        ),
        migrations.AlterField(
            model_name='events',
            name='urlNameEu',
            field=models.CharField(max_length=103),
        ),
    ]
