# Generated by Django 5.0.4 on 2024-05-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0012_alter_events_attachment_alter_events_companyes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='urlEventEs',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='events',
            name='urlEventEu',
            field=models.CharField(max_length=255),
        ),
    ]
