# Generated by Django 5.0.4 on 2024-05-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0013_alter_events_urleventes_alter_events_urleventeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='openingHoursEs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='openingHoursEu',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
