# Generated by Django 5.0.4 on 2024-05-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0014_alter_events_openinghourses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='openingHoursEs',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='openingHoursEu',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
