# Generated by Django 5.0.4 on 2024-06-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0015_alter_events_openinghourses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='images',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
